version: 2

workflows:
  version: 2
  workflow:
    jobs:
      - test-2.7
      - test-3.7

defaults: &defaults
  steps:
  - checkout
  - run:
      name: Install dependencies
      command: |
        GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" \
          sudo -E pip install -r requirements.txt
  - run:
      name: Test
      command: python setup.py test

jobs:
  test-2.7:
    <<: *defaults
    docker:
    - image: circleci/python:2.7
    - image: mongo:3.2.19
    - image: redis:3.2.6
  test-3.7:
    <<: *defaults
    docker:
    - image: circleci/python:3.7
    - image: mongo:3.2.19
    - image: redis:3.2.6
